{
  "openapi": "3.0.0",
  "info": {
    "description": "Essa é uma documentação sobre o Atlas API.",
    "version": "1.0.0",
    "title": "Atlas",
    "contact": {
      "email": "l.servo@hotmail.com"
    }
  },
  "host": "localhost:3000",
  "basePath": "/api-docs",
  "tags": [
    {
      "name": "users",
      "description": "Gerenciamento de usuários"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Cria um novo usuário",
        "operationId": "createUser",
        "produces": [
          "application/json"
        ],
        "requestBody": {
          "description": "Campos obrigatórios para a criação de um usuário.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Rocketseat",
                "email": "oi@rocketseat.com.br"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Operação realizada com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "admin": {
                      "type": "boolean"
                    },
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "admin": false,
                  "id": "a32d8169-56ef-4d48-a2c1-a595ff748116",
                  "name": "Rocketseat",
                  "email": "oi@rocketseat.com.br",
                  "created_at": "2021-03-10T22:10:32.992Z",
                  "updated_at": "2021-03-10T22:10:32.992Z"
                }
              }
            }
          },
          "400": {
            "description": "Email já está sendo utilizado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "error": "This email is already in use"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Retorna todos os usuários",
        "description": "Somente usuário ```admin``` pode acessar",
        "operationId": "listAllUsers",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user_id",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "admin": {
                      "type": "boolean"
                    },
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                },
                "example": [
                  {
                    "admin": true,
                    "id": "a32d8169-56ef-4d48-a2c1-a595ff748116",
                    "name": "Rocketseat",
                    "email": "oi@rocketseat.com.br",
                    "created_at": "2021-03-10T22:10:32.992Z",
                    "updated_at": "2021-03-10T22:10:32.992Z"
                  },
                  {
                    "admin": false,
                    "id": "a32d8169-56ef-4d48-a2c1-a595ff748116",
                    "name": "Lucas Servo",
                    "email": "l.servo@hotmail.com",
                    "created_at": "2021-03-10T22:10:32.992Z",
                    "updated_at": "2021-03-10T22:10:32.992Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Usuário sem permissão ou usuário não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "error": "You need to be an administrator to list all users."
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Retorna um usuário específico",
        "operationId": "userProfile",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "ID do usuário",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "admin": {
                      "type": "boolean"
                    },
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "admin": false,
                  "id": "a32d8169-56ef-4d48-a2c1-a595ff748116",
                  "name": "Lucas Servo",
                  "email": "l.servo@hotmail.com",
                  "created_at": "2021-03-10T22:10:32.992Z",
                  "updated_at": "2021-03-10T22:10:32.992Z"
                }
              }
            }
          },
          "400": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "error": "User not found."
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": [
          "users"
        ],
        "summary": "Torna um usuário admin",
        "operationId": "turnAdmin",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "admin": {
                      "type": "boolean"
                    },
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "admin": true,
                  "id": "a32d8169-56ef-4d48-a2c1-a595ff748116",
                  "name": "Lucas Servo",
                  "email": "l.servo@hotmail.com",
                  "created_at": "2021-03-10T22:10:32.992Z",
                  "updated_at": "2021-03-10T22:10:32.992Z"
                }
              }
            }
          },
          "400": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "error": "User not found."
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "id?": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "admin?": {
          "type": "boolean"
        },
        "email": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      },
      "xml": {
        "name": "User"
      }
    }
  }
}